export const moviesMock = {
  genres: [
    { id: 1, title: "Драмы", path: "/movies" },
    { id: 2, title: "Криминал", path: "/movies" },
    { id: 3, title: "Мультфильмы", path: "/movies" },
    { id: 4, title: "Фантастика", path: "/movies" },
    { id: 5, title: "Боевики", path: "/movies" },
    { id: 6, title: "Комедии", path: "/movies" },
    { id: 7, title: "Фэнтези", path: "/movies" },
    { id: 8, title: "Детективы", path: "/movies" },
    { id: 9, title: "Триллеры", path: "/movies" },
    { id: 10, title: "Биография", path: "/movies" },
    { id: 11, title: "Мелодрамы", path: "/movies" },
    { id: 12, title: "Вестерны", path: "/movies" },
    { id: 13, title: "Музыкальные", path: "/movies" },
    { id: 14, title: "История", path: "/movies" },
    { id: 15, title: "Приключения", path: "/movies" },
    { id: 16, title: "Аниме", path: "/movies" },
    { id: 17, title: "Ужасы", path: "/movies" },
    { id: 18, title: "Мюзиклы", path: "/movies" },
    { id: 19, title: "Военные", path: "/movies" },
    { id: 20, title: "Спортивные", path: "/movies" },
    { id: 21, title: "Семейные", path: "/movies" },
  ],

  country: [
    { id: 1, title: "Русское", path: "/movies" },
    { id: 2, title: "Американское", path: "/movies" },
    { id: 6, title: "Советское", path: "/movies" },
  ],

  years: [
    { id: 2023, title: "Фильмы 2023 года", path: "/movies" },
    { id: 2022, title: "Фильмы 2022 года", path: "/movies" },
    { id: 2021, title: "Фильмы 2021 года", path: "/movies" },
    { id: 2020, title: "Фильмы 2020 года", path: "/movies" },
  ],

  collection: [
    { title: "Новинки", path: "#" },
    { title: "Подборки", path: "#" },
    { title: "Иви.Рейтинг", path: "#" },
    { title: "Скоро на Иви", path: "#" },
    { title: "Трейлеры", path: "#" },
    { title: "Что посмотреть", path: "#" },
    { title: "Фильмы в HD", path: "#" },
    { title: "Выбор Иви", path: "#" },
    { title: "Новинки подписки", path: "#" },
    { title: "Фильмы Amediateka", path: "#" },
    { title: "Популярные фильмы", path: "#" },
    { title: "Фильмы Иви", path: "#" },
  ],
};
