export { BannerSlider } from "./ui/BannerSlider/BannerSlider";
export { FilterByGenre } from "./ui/FilterByGenre/FilterByGenre";
export { FilterByTag } from "./ui/FilterByTag/FilterByTag";
export { Footer } from "./ui/Footer/Footer";
export { Header } from "./ui/Header/Header";
export { MainFilter } from "./ui/MainFilter/MainFilter";
export { MovieSlider } from "./ui/MovieSlider/MovieSlider";
export { PersonSlider } from "./ui/PersonSlider/PersonSlider";
export { TopMovieSlider } from "./ui/TopMovieSlider/TopMovieSlider";
